name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew && ls && git clone https://huggingface.co/spaces/Duswishdb/Xc/
    
    - name: move directory
      run: ls && mv Xc/app/src/main/assets app/src/main/
    
    - name: list
      run: ls app/src/main && du -sh app/src/main 
      
    - name: Delete existing model 
      run: rm app/src/main/assets/model/unet/* && rm -rf app/src/main/assets/model/vae_decoder/* && rm -rf app/src/main/assets/model/text_encoder/*
      
    - name: Download model 
      run: wget -O app/src/main/assets/model/unet/model.ort 'https://huggingface.co/Androidonnxfork/test/resolve/main/fp16fullonnxsdquantized_in_ort/beautifulrealv6%2Cmajicmix%2Ccyberreal%2Cepicrealism%2C/cyberrealistic_v32/unet/model.ort'
    - name: Download vae
      run: wget -O app/src/main/assets/model/vae_decoder/model.ort 'https://huggingface.co/Androidonnxfork/test/resolve/main/fp16fullonnxsdquantized_in_ort/Never-ending-dream(NED(vae))/vae_decoder/model.ort'
   
    - name: Download text_encoder 
      run: wget -O app/src/main/assets/model/text_encoder/model.ort 'https://huggingface.co/Androidonnxfork/test/resolve/main/fp16fullonnxsdquantized_in_ort/deliberate%2Cdreamshaper/dreamshaper*/text_encoder/model.ort'
    
    - name: check Downloaded model
      run: ls app/src/main/assets/model/unet/*

      
    - name: Set current date as env variable

      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      

  #  - name: Set repository name as env variable

     # run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

    - name: Set deliberate as env variable

      run: echo "cyberrealv32=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV  
   
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: build the apk 
      run: ./gradlew assembleDebug
   # - name: zip
   #   run: zip -r deliberate.zip app/build/outputs/apk
    
    - name: bash upload 
      run: curl bashupload.com -T app/build/outputs/apk/release/*apk
    
    


     
#    - name: Build apk release project (APK) - ${{ env.main_project_module }} module

#      run: ./gradlew assemble

      

    - name: Check built apk 
      run: ls app/build/outputs/ && ls app/build/outputs/apk/* && du -sh app/build/outputs/apk/*
    - name: Upload APK Debug - ${{ env.repository_name }}

      uses: actions/upload-artifact@v3

      with:

          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated

          path: app/build/outputs/apk/debug/

#    - name: Upload APK Release - ${{ env.repository_name }}

#      uses: actions/upload-artifact@v3

#      with:

#          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated

#          path: app/build/outputs/apk/release/

#    - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}

#      uses: actions/upload-artifact@v3

#      with:

#          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated

#          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
     
